[project]
name = "leapfrogai-backend-ctransformers"
version = "0.1.0"
dependencies = [
    "leapfrogai >= 0.3.3",
    "ctransformers >= 0.2.27",
]
requires-python = ">=3.11.4"

[project.optional-dependencies]
dev = ["pip-tools", "pytest", "black", "isort"]

[tool.pip-tools]
generate-hashes = false