package:
  create:
    set:
      image_repository: "defenseunicorns/leapfrogai/ctransformers"
      version: 0.0.1
      name: ctransformers
    max_package_size: "1000000000"
  deploy:
    set:
      limits_cpu: 1
      limits_memory: 4Gi
      limits_gpu: 0
      requests_cpu: 1
      requests_memory: 4Gi
      requests_gpu: 0
      name: ctransformers
      image_repository: "defenseunicorns/leapfrogai/ctransformers"
      version: 0.0.1