name: Dev Docker Image Build/Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  VERSION: dev

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }

      - name: Push images
        run: |
          make docker-build VERSION=$VERSION ARCH=amd64
          make docker-push VERSION=$VERSION ARCH=amd64