name: Release Docker Image Build/Push

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Disable shallow clone
        run: git fetch --unshallow

      - name: Set VERSION
        run: echo "VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV

      - name: Build image
        run: |
          make docker-build VERSION=$VERSION ARCH=amd64
          make docker-build VERSION=$VERSION ARCH=arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run:
          make docker-push VERSION=$VERSION ARCH=amd64
          make docker-push VERSION=$VERSION ARCH=arm64