
name: Release Docker Image Build/Push

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  IMAGE_NAME: leapfrogai/ctransformers
  VERSION: $GITHUB_REF_NAME

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: make docker-build VERSION=$VERSION

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: make docker-push VERSION=$VERSION