
name: Release Docker Image Build/Push

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Output Version
        run: |
          echo $VERSION
          echo ${{ env.VERSION }}

      - name: Build image
        run: make docker-build VERSION=$VERSION

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: make docker-push VERSION=$VERSION